trigger:

  branches:
    include:
      - main

stages:

  - stage: Terraform
    displayName: 'Provision Infrastructure'
    jobs:
      - job: Terraform_Apply
        displayName: 'Terraform Apply'
        pool:
          name: 'linux-hosted-agent'
        steps:

          # --------------------------------------------------------------------
          # Step 1: Setup Terraform Backend (non-interactive)
          # --------------------------------------------------------------------
          - script: |
              echo "Running Terraform backend setup..."
              chmod +x setup-tf-backend.sh
              ./setup-tf-backend.sh --non-interactive
            workingDirectory: $(System.DefaultWorkingDirectory)
            displayName: 'Setup Terraform Backend'

          # --------------------------------------------------------------------
          # Step 2: Download SSH public key for Terraform modules
          # --------------------------------------------------------------------
          - task: DownloadSecureFile@1
            name: download_ssh_key
            inputs:
              secureFile: 'azure_rsa.pub'

          - script: |
              echo "Copying SSH public key into Terraform module..."
              mkdir -p ~/.ssh
              cp $(download_ssh_key.secureFilePath) ~/.ssh/azure_rsa.pub

              # Ensure module folder exists
              mkdir -p terraform/modules/compute
              cp $(download_ssh_key.secureFilePath) modules/compute/azure_rsa.pub

              echo "Listing contents of terraform/modules/compute/"
              ls -al terraform/modules/compute/
            displayName: 'Extract SSH Public Key for Terraform'

          # --------------------------------------------------------------------
          # Step 3: Terraform Init / Plan / Apply
          # --------------------------------------------------------------------
          - task: AzureCLI@2
            inputs:
              azureSubscription: 'it-azure-connection'
              scriptType: bash
              scriptLocation: inlineScript
              workingDirectory: $(System.DefaultWorkingDirectory)
              inlineScript: |
                echo "##[group]Terraform Init / Plan / Apply"
                terraform init -input=false
                terraform plan -input=false -var-file="envs/dev.tfvars"
                terraform apply -input=false -auto-approve -var-file="envs/dev.tfvars"
                echo "##[endgroup]"

          # --------------------------------------------------------------------
          # Step 4: Output VM public IP for downstream pipelines
          # --------------------------------------------------------------------
          - script: |
              echo "Getting VM public IP from Terraform output..."
              VM_PUBLIC_IP=$(terraform output -raw vm_public_ip)
              echo "##vso[task.setvariable variable=vm_public_ip;isOutput=true]$VM_PUBLIC_IP"
              echo "VM Public IP: $VM_PUBLIC_IP"
            workingDirectory: $(System.DefaultWorkingDirectory)
            displayName: 'VM Public IP'
